<!-- FUCK THIS SHIT IM OUT 
hata facebook alltof mikið

bara nei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei
neineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineinei


<div id="fb-root"></div>
<script> // FB JS SDK
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2&appId=1382155295164635';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<script>
    window.fbAsyncInit = function () {
        FB.api(
        '/1973848686216471',
        'GET',
        {},
        function(response) {
            console.log(response);
        }
        );
    };
</script>




<style>
    /* Facebook gallery section */
   /* section#gallery {
        padding: 5% 0;
        text-align: center;
    }
    
    section#gallery a {
        background-size: cover;
        background-position: center;
        width: 250px;
        height: 250px;
        margin: 1%;
        display: inline-block;
    }*/
</style>
<!--<div class='embedsocial-album' data-ref="e2c81c716f64c54ad368a7c73e10379af71f4d3f"></div><script>(function(d, s, id){var js; if (d.getElementById(id)) {return;} js = d.createElement(s); js.id = id; js.src = "https://embedsocial.com/embedscript/ei.js"; d.getElementsByTagName("head")[0].appendChild(js);}(document, "script", "EmbedSocialScript"));</script>

<script>
    let x = document.getElementsByClassName("img-responsive");
    console.log(x);
</script>


<section id="gallery">
<?php
/*
    $access_token="EAAV9oVEwZAX4BAJBF1xuFbvkZBhSkbAd9hrnZCc9gHOvUd6xEOGH3OPznRioUr2ECVI9jTEXLB06ZCHWHqyNN5rR5jCzD2L1ZB6S0tJXnHigzZAXlRtZAWHkznGiBQ9JHTzQaO6lM9VXBYLKuwssQTcxi730n0efkrO23jRxHiYZCBixa5IVwenpQLuiDrRSzQMZD";
    $json_link = "https://graph.facebook.com/v2.3/1973848686216471/photos?fields=images,name,link&limit=9&access_token={$access_token}";
    $json = file_get_contents($json_link);
    $result = json_decode($json);
    $j = 0;
    foreach($result->data as $image) {
        // Look for third image (instead of large version)
        for($i = 2; $i > 0; $i--) {
            if(isset($image->images[$i])) {
                $name = (isset($image->name) ? $image->name : "");
                echo "<a class=\"photo$j\" href=\"{$image->link}\" title=\"{$name}\" rel=\"external\" style=\"background-image: url('{$image->images[$i]->source}')\"></a>";
                break;
            }
        }
        if($j % 3 == 2) {
            echo "<br />";
        }
        $j++;
    }*/
?>
</section> -->

<!--<iframe scrolling="no" marginheight="0" frameborder="0" width="551" style="height: 582px;" src="https://socialgalleria.com/gallery.php?id=Austfirsk&rows=4&margin=10&cols=3&width=170&font_size=11&title_color=000&hide_next_back=0&share_buttons=1&shape=rectangle&frame=1&token=b6f65693-2fe9-11e9-9e80-4b383973989e"></iframe>-->